# Prefer the DisplayPort monitor (Q27G4_WS) for NVIDIA HDMI/DP audio.
device.profile.priority.rules = [
  {
    matches = [
      {
        device.name = "alsa_card.pci-0000_01_00.1"
      }
    ]
    actions = {
      update-props = {
        priorities = [ "output:hdmi-stereo-extra1", "output:hdmi-stereo" ]
      }
    }
  }
]
